Tworcy/Models/ErrorViewModel.cs
using System;

namespace Tworcy.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tworcy/Models/Spis/AssetDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TworcyData.Models;

namespace Tworcy.Models.Spis
{
    public class AssetDetailModel
    {
        public Tworca Tworca { get; set; }
        public IEnumerable<Zdjecie> Zdjecia { get; set; }
    }
}

Tworcy/Models/Spis/AssetIndexListingModel.cs
namespace Tworcy.Models.Spis
{
    public class AssetIndexListingModel
    {
        public int Id { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Zdjecie { get; set; }
        public string Biogram { get; set; }
    }
}

Tworcy/Models/Spis/AssetIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tworcy.Models.Spis
{
    public class AssetIndexModel
    {
        public IEnumerable<AssetIndexListingModel> Assets { get; set; }
    }
}

Tworcy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tworcy.Models;

namespace Tworcy.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tworcy/Controllers/SpisController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Tworcy.Models.Spis;
using TworcyData;

namespace Tworcy.Controllers
{
    public class SpisController : Controller
    {
        private ITworcyAsset _assets;

        public SpisController(ITworcyAsset assets)
        {
            _assets = assets;
        }

        public IActionResult Index()
        {
            var assetModels = _assets.GetAll();

            var listingResult = assetModels
                .Select(result => new AssetIndexListingModel
                {
                    Id = result.Id,
                    Imie = result.Imie,
                    Nazwisko = result.Nazwisko,
                    Zdjecie = result.Zdjecie,
                    Biogram = result.Biogram
                });

            var model = new AssetIndexModel()
            {
                Assets = listingResult
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var tworca = _assets.GetById(id);
            var galeria = _assets.GetTworcaGallery(tworca);

            var model = new AssetDetailModel
            {
                Tworca = tworca,
                Zdjecia = galeria
            };

            return View(model);
        }
    }
}

Tworcy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tworcy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tworcy</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tworcy</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spis" asp-action="Index">Spis</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Tworcy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Tworcy/Views/Spis/Detail.cshtml
@model Tworcy.Models.Spis.AssetDetailModel

<div class="row">
    <div class="col-12">
        <img src="@Model.Tworca.Zdjecie" class="mx-auto mx-md-3 d-block float-md-left img-thumbnail" alt="Alternate Text" />
        <div class="text-justify">@Html.Raw(@Model.Tworca.Biogram)</div>
    </div>
</div>

<br />

<div class="row">
    <div class="col-12">
        <div class="btn-group">
            @if (@Model.Tworca.Bibliografia != null)
            {
                <button type="button" class="btn btn-primary" data-toggle="collapse" href="#bibliografia" role="button" aria-expanded="false" aria-controls="collapseExample">Bibliografia</button>
            }
            @if (@Model.Tworca.Wystawy != null)
            {
                <button type="button" class="btn btn-primary">Wystawy</button>
            }
            @if (@Model.Tworca.Nagrody != null)
            {
                <button type="button" class="btn btn-primary">Nagrody</button>
            }
            @if (@Model.Tworca.Teksty != null)
            {
                <button type="button" class="btn btn-primary">Teksty</button>
            }
            @if (@Model.Tworca.Audio != null)
            {
                <button type="button" class="btn btn-primary">Audio</button>
            }
            @if (@Model.Tworca.Kontakt != null)
            {
                <button type="button" class="btn btn-primary">Kontakt</button>
            }
            @if (@Model.Zdjecia.Count() > 0)
            {
                <button type="button" class="btn btn-primary" data-toggle="collapse" href="#galeria" role="button" aria-expanded="false" aria-controls="collapseExample">Galeria</button>
            }
        </div>
    </div>
</div>

<br />

<div class="row">
    <div class="col-12">
        <div class="collapse" id="galeria">
            <div class="row">
                @foreach (var asset in Model.Zdjecia)
                {
                    <div class="col-auto">
                        <div class="tworca">
                            <img class="img-thumbnail" data-toggle="modal" data-target="#zdjecie@asset.Id" src="@asset.zdjecieUrl" alt="@asset.zdjecieUrl">
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="collapse" id="bibliografia">
            @Model.Tworca.Bibliografia
        </div>

    </div>
</div>

Tworcy/Views/Spis/Index.cshtml
@model Tworcy.Models.Spis.AssetIndexModel

<h3>Katalog Twórców</h3>

<div class="row">
    @foreach (var asset in Model.Assets)
    {
        <div class="col-auto">
            <div class="tworca">
                <a asp-controller="Spis" asp-action="Detail" asp-route-id="@asset.Id" class="cardLink">
                    <img class="img-thumbnail" src="@asset.Zdjecie" alt="Card image cap">
                </a>
                    <p>@asset.Imie @asset.Nazwisko</p>
                
            </div>
        </div>
    }
</div>